doc_man/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations'}
  authenticate :user do
      resources :documents do
        get 'categories', on: :member
        resources :suggestions do
          resources :suggestion_user_comments
        end
      end
      resources :categories
      resources :users
      root to: 'documents#index'
      get "my_documents" => 'documents#my_documents_index', :as => :my_documents
      get "/add_like" => "likes#addLike"
      get "/remove_like" => "likes#removeLike"
  end
  get "public_documents" => 'documents#public_documents_index', :as => :public_documents
  get "public_show" => 'documents#public_show', :as => :public_show
  get "/test" => "documents#markdownHtml"
  post "/collaborators" => "documents#updateCollaborators"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

doc_man/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super Doc-Man -- Your Favorite Document Manager</title>
    <link rel="shortcut icon" href='<%= asset_path("logofinal-head.png") %>'/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <br>
    <nav class="navbar navbar-toogleable-md navbar-fixed-top navbar-inverse" style="line-height: 50px;">

      <div class="container-fluid">
        <div>
        <% if user_signed_in? %>
          <%= link_to image_tag("logofinal.png", :width=>"200px", :height=>"46px"), documents_path, id: "logo" %>
        <% else %>
          <%= link_to image_tag("logofinal.png", :width=>"200px", :height=>"46px"), public_documents_path, id: "logo" %>
        <% end %>
        <div>
        <div class="navbar-header" style="margin-bottom: 11px">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? %>
            <%= form_tag(documents_path, method: 'get', class: 'form-inline navbar-form navbar-left') do %>
              <%= search_field_tag 'search', params[:search], class: 'form-control', placeholder: 'Search'  %>
              <%= submit_tag "Submit", class: 'btn btn-primary', :name => nil %>
            <% end %>
          <% else %>
            <%= form_tag(public_documents_path, method: 'get', class: 'form-inline navbar-form navbar-left') do %>
              <%= search_field_tag 'search', params[:search], class: 'form-control', placeholder: 'Search'  %>
              <%= submit_tag "Submit", class: 'btn btn-default', :name => nil %>
            <% end %>
          <% end %>
            <nav style="line-height: 70px;">
                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                        <li>
                            <%= link_to documents_path do %>
                              <span class="fa fa-book" style="color:white; line-height: 40px;"></span>
                              Browse Documents
                            <% end %>
                        </li>
                        <li>
                            <%= link_to my_documents_path do %>
                              <span class="fa fa-book" style="color:white; line-height: 40px;"></span>
                              My Documents
                            <% end %>
                        </li>
                        <li>
                            <%= link_to categories_path do %>
                              <span class="fa fa-tags" style="color:white; line-height: 40px;"></span>
                              Categories
                            <% end %>
                        </li>
                        <li>
                            <%= link_to new_user_registration_path do %>
                              <span class="fa fa-user-plus" style="color:white; line-height: 40px;"></span>
                              New User
                            <% end %>
                        </li>
                        <li>
                            <%= link_to(destroy_user_session_path, :method => :delete) do %>
                              <span class="fa fa-sign-out" style="color:white; line-height: 40px;"></span>
                              Logout
                            <% end %>
                        </li>
                    <%else %>
                        <li>
                            <%= link_to public_documents_path do %>
                              <span class="fa fa-book" style="color:white; line-height: 40px;"></span>
                              Browse Documents
                            <% end %>
                        </li>
                        <li>
                            <%= link_to new_user_session_path do %>
                              <span class="fa fa-sign-out" style="color:white; line-height: 40px;"></span>
                              Sign In
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </nav>
        </div>
      </nav>
    </div>
    <div class="container" style='margin-top:70px'>
      <% if not notice.nil? %>
        <div class="alert alert-success" role="alert"><%= notice %><a class="close" data-dismiss="alert" href="#">&times;</a></div>
      <% end %>
      <% if not alert.nil? %>
        <div class="alert alert-danger" role="alert"><%= alert %><a class="close" data-dismiss="alert" href="#">&times;</a></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

<style>
@media (min-width: 768px) and (max-width: 1150px) {
    .navbar-collapse.collapse {
        display: none !important;
    }
    .navbar-collapse.collapse.in {
        display: block !important;
    }
    .navbar-header .collapse, .navbar-toggle {
        display:block !important;
    }
    .navbar-header {
        float:none;
    }
}
</style>