doc_man/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations'}
  authenticate :user do
      resources :documents do
        get 'categories', on: :member
        resources :suggestions do
          resources :suggestion_user_comments
        end
      end
      resources :categories
      resources :users
      root to: 'documents#index'
      get "my_documents" => 'documents#my_documents_index', :as => :my_documents
      get "/add_like" => "likes#addLike"
      get "/remove_like" => "likes#removeLike"
  end
  get "public_documents" => 'documents#public_documents_index', :as => :public_documents
  get "public_show" => 'documents#public_show', :as => :public_show
  get "/test" => "documents#markdownHtml"
  post "/collaborators" => "documents#updateCollaborators"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

doc_man/app/models/document.rb
class Document < ApplicationRecord
  has_many :document_categories,  dependent: :destroy
  has_many :document_accesses,  dependent: :destroy
  has_many :categories, through: :document_categories,  dependent: :destroy
  has_many :users, through: :document_accesses,  dependent: :destroy
  has_many :suggestions,  dependent: :destroy
  has_many :likes,  dependent: :destroy 
  validates :title, {
  	length: { minimum: 3,  maximum: 50 },
  	presence: true,
  	uniqueness: true
  	}
  validates :text, {
  	length: { minimum: 10 },
  	presence: true
  }
  accepts_nested_attributes_for :categories
  belongs_to :user
  def to_s
    return title
  end

end

doc_man/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy, :categories]

  # GET /documents
  # GET /documents.json
  def index
    @current_user = current_user
    if !params[:search].nil?
      @documents = (Document.where("is_public = 'true' AND lower(title) like ?", "%#{params[:search].downcase}%").order('title ASC') +
                    current_user.collab_documents.where("title  like ?", "%#{params[:search].downcase}%").order('title ASC')).uniq.sort_by{'title ASC'}
    else
      @documents = (current_user.collab_documents.order('title ASC') + Document.where("is_public = 'true'")).uniq.sort_by{'title ASC'}
    end
  end

  # GET /documents
  # GET /documents.json
  def my_documents_index
      @documents = current_user.collab_documents.order('title ASC')
  end

  # GET /documents
  # GET /documents.json
  def public_documents_index
    if !params[:search].nil?
      @documents = Document.where("is_public = 'true' AND lower(title) like ?", "%#{params[:search].downcase}%").order('title ASC')
    else
      @documents = Document.where("is_public = 'true'").order('title ASC')
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @current_user = current_user
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    markdown_text = markdown.render(@document.text)
    @document.text = markdown_text
  end

  # GET /documents/1
  # GET /documents/1.json
  def public_show
    @document = Document.find(params[:document])
      if @document.is_public
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
        markdown_text = markdown.render(@document.text)
        @document.text = markdown_text
      else
        respond_to do |format|
          format.html { redirect_to public_documents_path, alert: 'Unable to show private document.' }
          format.json { render json: @document.errors, status: :unprocessable_entity }
        end
      end
  end

  # GET /documents/new
  def new
    @document = Document.new
    @document.categories = [Category.new]
    @current_user = current_user
  end

  # GET /documents/1/edit
  def edit
    doc = params[:document]
    if !current_user.collab_documents.include?(@document)
      respond_to do |format|
        format.html { redirect_to documents_path, alert: "You don't have permissions to edit private document." }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def categories
  end


  def markdownHtml
    text_to_markDown = params[:rc_text]
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    markwond_text = markdown.render(text_to_markDown)
    jsonObject = {"text" => markwond_text}
    respond_to do |format|
      format.html
      format.json { render json: jsonObject }
    end
  end


  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[document_params])
    @document.categories << Category.find(params[:document][:categories].drop(1))
    @document.users << User.find(params[:document][:users].drop(1))
    @document.users.push(current_user)
    @document.title = params[:document][:title]
    @document.text = params[:document][:text]
    @document.user = current_user

    if params[:document][:is_public] == 'true'
      @document.is_public = true
    else
      @document.is_public = false
    end
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    if not Category.find(params[:document][:categories].drop(1)).blank?
      @document.categories = []
      @document.categories << Category.find(params[:document][:categories].drop(1))
    end
    params[:document][:categories] << Category.find(params[:document][:categories].drop(1))

    if params[:document][:is_public] == 'true'
      @document.is_public = true
    else
      @document.is_public = false
    end

    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def updateCollaborators
    @document = Document.find(params[:document][:id])
    @document.users = []
    @document.users << User.find(params[:document][:users])
    @document.users.push(current_user)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    if current_user.collab_documents.include?(@document)
      @document.destroy
      respond_to do |format|
        format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to documents_url, alert: "You don't have permissions to destroy private document." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_document
      if !params[:document_id].nil?
        @document = Document.find(params[:document_id])
      else
        @document = Document.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params[:document].permit(:title, :is_public, :text, :categories => [], :users => [])
    end
end

doc_man/app/helpers/documents_helper.rb
module DocumentsHelper
end

doc_man/app/views/documents/_form.html.erb
<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <div class="field">
    <%= f.text_field :title %>
  </div>

  <%= f.label :categories %>
  <div class="field">
    <%= f.collection_select(:categories, Category.all, :id, :title, {}, {:style => "width:573px", :multiple => true, :class => 'category_selector'}) %>
  </div>

  <table class = "table table-hover table-striped">
  	<tr>
  		<th>
        <div class="panel panel-primary" >
          <div class = "panel-heading">
            <%= f.label :text %>
          </div>
          <div class="panel-body">
            <%= f.text_area :text, id: "text_to_edit",style: "margin: 0px; height: 410px; width: 573px;" %>
          </div>
        </div>
  		</th>
  		<th>
  			  <div class="panel panel-primary" >
            <div class = "panel-heading">
              <%= f.label :preview %>
            </div>
            <div class="panel-body">
              <div id='preview'>
                <p >
                  <%= markdown(@document.text) %>
                </p>
              </div>
              <p id="demo" ></p>
            </div>
  			  </div>
  		</th>
  	</tr>
  </table>

  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $(".category_selector").select2();
  });

  $("#text_to_edit").keyup(function() {
  	var rc_to_send = document.getElementById ( "text_to_edit" ).value;
  	if (document.contains(document.getElementById("preview"))) {
              document.getElementById("preview").remove();
  	}
      $.ajax({
          type: "GET",
          dataType: "json",
          url: "/test",
          data: {
              rc_text: rc_to_send // < note use of 'this' here
          },
          success: function(json) {
            //document.getElementById("demo").className = "panel panel-primary";
          	document.getElementById("demo").innerHTML = json.text;
          	//result = $.parseJSON(json);

          },
          error: function(json) {
              alert('error');
          }
      });
  });

</script>

doc_man/app/views/documents/edit.html.erb
<!-- Modal -->
<div class="modal fade" id="editCollaboratorsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit collaborators</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 offset-md-2">
            <%= collection_select(:users, :user_id, User.where.not(id: @document.users.uniq), :id, :to_s, {},{:size => 6}) %>
          </div>
          <div class="col-md-6 offset-md-2" >
            <%= collection_select(:users, :collaborators_users_id, @document.users.uniq, :id, :to_s, {},{:size => 6}) %>
          </div>
        </div>
        <div class = "row">
          <div class = "col-md-6">
            <button type="button" onclick="addOrRemoveCollaborator('addCollaborator')" class="btn btn-primary">Add collaborator</button>
          </div>
          <div class = "col-md-6">
            <button type="button" onclick="addOrRemoveCollaborator('removeCollaborator')" class="btn btn-danger">Remove collaborator</button>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" onclick ="updateCollaborators(<%= @document.id %>)" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<h1>Editing Document</h1>
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this @document from being saved:</h2>
      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.label :title %>
  <div class="field">
    <%= f.text_field :title, :style => "width:573px" %>
  </div>
  <strong>Change Categories</strong>
  <div class="field">
    <%= f.collection_select(:categories, Category.all, :id, :title, {:selected => @document.categories.ids}, {:style => "width:573px", :multiple => true, :class => 'category_selector'}) %>
  </div>
  <strong>Current collaborators</strong>
  <div class="field">
    <%= f.collection_select(:users, User.where.not(id: @document.user.id), :id, :to_s, {:selected => @document.users.ids.uniq}, {:style => "width:573px", :multiple => true, :class => 'category_selector', :disabled => "disabled"}) %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editCollaboratorsModal">
      Edit collaborators
    </button>
  </div>
  <br>

	<div class = "row">
		<div class = "col-md-6 col-ms-12">
      <div class="panel panel-primary" >
        <div class = "panel-heading">
          <%= f.label :text %>
        </div>
        <div class="panel-body">
          <%= f.text_area :text, id: "text_to_edit",class: "col-md-12 col-ms-12 col-xs-12" %>
        </div>
      </div>
		</div>

    <div class = "hidden-xs hidden-sm col-md-6">
      <div class="panel panel-primary" >
        <div class = "panel-heading">
          <%= f.label :preview %>
        </div>
        <div class="panel-body">
          <div id='preview'>
            <p >
              <%= markdown(@document.text) %>
            </p>
          </div>
          <p id="real_time_preview" ></p>
        </div>
      </div>
    </div>
	</div>
<%= f.label :is_a_public_document %>
<% if @document.is_public? %>
  <%= f.check_box :is_public, {:checked => "checked"}, 'true', 'false' %>
<% else %>
  <%= f.check_box :is_public,{}, 'true', 'false' %>
<% end %>

  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

<%= link_to 'Show', @document, class: "btn btn-primary", style: "color:white" %> |
<%= link_to 'Back', documents_path, class: "btn btn-danger", style: "color:white" %>

<script>

$('textarea').each(function () {
  this.setAttribute('style', 'height:' + (this.scrollHeight) + 'px;overflow-y:hidden; min-height:350px');
}).on('input', function () {
  this.style.height = 'auto';
  this.style.height = (this.scrollHeight) + 'px';
});

$(document).ready(function(){
  $(".category_selector").select2();

});

function updateCollaborators(document_id){
  var collaboratorsSelect = document.getElementById("users_collaborators_users_id").options;

  var collaboratorsIds = []
  for(idx = 0; idx < collaboratorsSelect.length; idx++){
    collaboratorsIds[idx] = collaboratorsSelect[idx].value;
  }

  var users = {
    users: collaboratorsIds,
    id: document_id
  }

  $.ajax({
        type: "POST",
        dataType: "json",
        url: "/collaborators",
        data: {
            document: users // < note use of 'this' here
        },
        success: function(json) {
          $('#editCollaboratorsModal').modal('toggle');
          location.reload();
          //document.getElementById("demo").className = "panel panel-primary";
          //document.getElementById("real_time_preview").innerHTML = json.text;
          //result = $.parseJSON(json);

        },
        error: function(json) {
            alert('error');
        }
    });

}

function addOrRemoveCollaborator(action) {

    var originSelect;
    var finalSelect;
    // Check if we need add the collaborator or remove.
    if(action == "addCollaborator"){
      originSelect= document.getElementById("users_user_id");
      finalSelect = document.getElementById("users_collaborators_users_id");
    }
    else{
      // Remove collaborator.
      originSelect= document.getElementById("users_collaborators_users_id");
      finalSelect = document.getElementById("users_user_id");
    }

    // Check if we have something select.
    var userId = originSelect.value;
    if (userId != ""){
      // Get the user info.
      var currentIndex = originSelect.selectedIndex;
      var userName = originSelect.options[currentIndex].text;

      // Add the user to the finalSelect.
      var newOption = document.createElement("option");
      newOption.text = userName;
      newOption.value = userId;
      finalSelect.options.add(newOption, 1);

      // Delete the user to the originSelect.
      originSelect.options.remove(currentIndex);
    }

}

$("#text_to_edit").keyup(function() {
	var rc_to_send = document.getElementById ( "text_to_edit" ).value;
	if (document.contains(document.getElementById("preview"))) {
            document.getElementById("preview").remove();
	}
    $.ajax({
        type: "GET",
        dataType: "json",
        url: "/test",
        data: {
            rc_text: rc_to_send // < note use of 'this' here
        },
        success: function(json) {
          //document.getElementById("demo").className = "panel panel-primary";
        	document.getElementById("real_time_preview").innerHTML = json.text;
        	//result = $.parseJSON(json);

        },
        error: function(json) {
            alert('error');
        }
    });
});
</script>

doc_man/app/views/documents/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Documents</h1>
  </div>
  <table class='table table-hover table-striped'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Category</th>
        <th>Permissions</th>
        <th colspan="3">Actions</th>
        <th>Suggestions</th>
      </tr>
    </thead>

    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= document.title %></td>
          <td><%= truncate(document.text.html_safe, length:75) %></td>
          <td><p>
            <% document.categories.each do |c| %>
              <%= c%><%if not c.equal? document.categories.last %>, <% end %>
            <% end %>

          </p></td>
          <td>
            <%if document.is_public %>
                Public
            <%else%>
                Private
            <%end%>
          </td>
          <td><%= link_to 'Show', document, class: "btn btn-info", style: "color:white" %></td>
          <% if @current_user.collab_documents.include?(document) or @current_user.documents.include?(document)  %>
            <td><%= link_to 'Edit', edit_document_path(document), class: "btn btn-primary", style: "color:white" %></td>
            <td><%= link_to 'Destroy', document, class: "btn btn-danger", style: "color:white" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
          <td>
            <%= link_to document_suggestions_path(document), class: "btn btn-primary-2", style: "color:white"  do %>
              <span class="fa fa-comment" style="color:white;"></span>
              <%= document.suggestions.length %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>


<br>

<%= link_to 'New Document', new_document_path, class: "btn btn-primary", style: "color:white"  %>

doc_man/app/views/documents/my_documents_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>My Documents</h1>
  </div>
  <table class='table table-hover table-striped'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Category</th>
        <th>Permissions</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @documents.uniq.each do |document| %>
        <tr>
          <td><%= document.title %></td>
          <td><%= truncate(document.text.html_safe, length:75) %></td>
          <td><p>
            <% document.categories.each do |c| %>
              <%= c%><%if not c.equal? document.categories.last %>, <% end %>
            <% end %>

          </p></td>
          <td>
            <%if document.is_public %>
                Public
            <%else%>
                Private
            <%end%>
          </td>
          <td><%= link_to 'Show', document, class: "btn btn-info", style: "color:white" %></td>
          <td><%= link_to 'Edit', edit_document_path(document), class: "btn btn-primary", style: "color:white" %></td>
          <td><%= link_to 'Destroy', document, class: "btn btn-danger", style: "color:white" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>


<br>

<%= link_to 'New Document', new_document_path, class: "btn btn-primary", style: "color:white"  %>

doc_man/app/views/documents/new.html.erb
<h1>New Document</h1>
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this @document from being saved:</h2>
      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.label :title %>
  <div class="field">
    <%= f.text_field :title %>
  </div>
  <%= f.label :categories %>
  <div class="field">
    <%= f.collection_select(:categories, Category.all, :id, :title, {}, {:style => "width:573px", :multiple => true, :class => 'category_selector'}) %>
  </div>
  <%= f.label :collaborators %>
  <div class="field">
    <%= f.collection_select(:users, User.where.not(id: @current_user.id), :id, :to_s, {}, {:style => "width:573px", :multiple => true, :class => 'category_selector'}) %>
  </div>
  <div class = "row">

    <div class = "col-md-6 col-ms-12">
      <div class="panel panel-primary" >
        <div class = "panel-heading">
          <%= f.label :text %>
        </div>
        <div class="panel-body">
          <%= f.text_area :text, id: "text_to_edit",style: "min-height:350px", class: "col-md-12 col-ms-12 col-xs-12" %>
        </div>
      </div>
    </div>

    <div class = "hidden-xs hidden-sm col-md-6" >
      <div class="panel panel-primary" style="min-width: 580px;" >
        <div class = "panel-heading">
          <%= f.label :preview %>
        </div>
        <div class="panel-body">
          <div id='preview'>
            <p >
              <%= @document.text %>
            </p>
          </div>
          <p id="demo" ></p>
        </div>
      </div>
    </div>
	</div>


  <div>
    <%= f.label :is_a_public_document %>
    <%= f.check_box :is_public, {}, 'true', 'false' %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

<%= link_to 'Back', documents_path, class: "btn btn-danger", style: "color:white" %>

<script>

$(document).ready(function(){
  $(".category_selector").select2();
});


$("#text_to_edit").keyup(function() {
	var rc_to_send = document.getElementById ( "text_to_edit" ).value;
	if (document.contains(document.getElementById("preview"))) {
            document.getElementById("preview").remove();
	}
    $.ajax({
        type: "GET",
        dataType: "json",
        url: "/test",
        data: {
            rc_text: rc_to_send // < note use of 'this' here
        },
        success: function(json) {
          //document.getElementById("demo").className = "panel panel-primary";
        	document.getElementById("demo").innerHTML = json.text;
        	//result = $.parseJSON(json);

        },
        error: function(json) {
            alert('error');
        }
    });
});
</script>

doc_man/app/views/documents/public_documents_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Documents</h1>
  </div>
  <table class='table table-hover table-striped'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Category</th>
        <th>Permissions</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= document.title %></td>
          <td><%= truncate(document.text.html_safe, length:75) %></td>
          <td><p>
            <% document.categories.each do |c| %>
              <%= c%><%if not c.equal? document.categories.last %>, <% end %>
            <% end %>

          </p></td>
          <td>
            <%if document.is_public %>
                Public
            <%else%>
                Private
            <%end%>
          </td>
          <td><%= link_to 'Show', public_show_path(:document => document), class: "btn btn-info", style: "color:white" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>


<br>

doc_man/app/views/documents/public_show.html.erb
<div class="panel panel-primary">
  <div class = "panel-heading">
    <h2>
      <strong><%= @document.title %></strong>
      <% if @document.is_public? %>
        <strong> [Public]<strong>
      <% else %>
        <strong> [Private]<strong>
      <% end %>
    </h2>
    <h6>
      <strong>Created by:</strong>
      <i>
        <%= @document.user.first_name + " " + @document.user.last_name %>
      </i>
    </h6>
    <% if !@document.users.uniq.empty? %>
      <h6>
        <i>
          <strong>Collaborators:</strong>
          <% @document.users.uniq.each do |c| %>
              <%= c  %>
              <% if not c.equal? @document.users.uniq.last %>
              ,
              <% end %>
          <% end %>
        </i>
      </h6>
    <% end %>

  </div>
  <div class="panel-body">
    <p>
      <%= raw @document.text %>
    </p>
  </div>
  <div class="panel-footer">
    <strong>Categories:</strong>
    <% @document.categories.each do |c| %>
        <%= c  %>
        <% if not c.equal? @document.categories.last %>
        |
        <% end %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', public_documents_path, class: "btn btn-success", style: "color:white" %>

doc_man/app/views/documents/show.html.erb
<div class="panel panel-primary">
  <div class = "panel-heading">
    <h2>
      <strong><%= @document.title %></strong>
      <% if @document.is_public? %>
        <strong> [Public]<strong>
      <% else %>
        <strong> [Private]<strong>
      <% end %>
    </h2>
    <h6>
      <strong>Created by:</strong>
      <i>
        <%= @document.user.first_name + " " + @document.user.last_name %>
      </i>
    </h6>
    <% if !@document.users.uniq.empty? %>
      <h6>
        <i>
          <strong>Collaborators:</strong>
          <% @document.users.uniq.each do |c| %>
              <%= c  %>
              <% if not c.equal? @document.users.uniq.last %>
              ,
              <% end %>
          <% end %>
        </i>
      </h6>
    <% end %>

  </div>
  <div class="panel-body">
    <p>
      <%= raw @document.text %>
    </p>
  </div>
  <div class="panel-footer">
    <div class = "row">
      <% if @current_user.id %>
        <% button_class = 'btn btn-link notActive' %>
        <% button_title = 'Like Document' %>
        <% span_class = 's-notActive' %>
        <% @current_user.likes.each do |like| %>
          <% if like.document == @document %>
            <% button_class = 'btn btn-link isActive' %>
            <% button_title = 'Unlike Document' %>
            <% span_class = 's-isActive' %>
            <% break %>
          <% end %>
        <% end %>
      <% end %>
      <div class = "col-md-6" align = "left">
        <strong>Categories:</strong>
        <% @document.categories.each do |c| %>
            <%= c  %>
            <% if not c.equal? @document.categories.last %>
            |
            <% end %>
        <% end %>
      </div>
      <div class = "col-md-6" align = "right">
        <span>
        <p id='people-like-<%= @document.id -%>' style="display:inline;">Likes: <%= @document.likes.length %></p>
        <button title="<%= button_title -%>" onclick="toggleLike(<%= @document.id -%>)" id="<%= @document.id -%>" type="button" class="<%= button_class -%>">
          <span id="span-<%= @document.id -%>" class="glyphicon glyphicon-heart <%= span_class -%>"></span>
        </button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class = "row">
  <div class = "col-md-6" align = "left">
    <% if @current_user.collab_documents.include?(@document) or @current_user.documents.include?(@document) %>
      <%= link_to 'Edit', edit_document_path(@document), class: "btn btn-primary", style: "color:white" %> |
    <%end%>
    <%= link_to 'Back', documents_path, class: "btn btn-success", style: "color:white" %>
  </div>
  <div class = "col-md-6" align = "right">
    <%= link_to document_suggestions_path(@document), class: "btn btn-primary-2", style: "color:white"  do %>
      <span class="fa fa-comment" style="color:white;"></span>
      <%= @document.suggestions.length %> Suggestions
    <% end %>
  </div>
</div>
<br><br>
<style>
.s-isActive {
    color: #d9534f;  // Hex for primary-danger
}
.s-notActive{
    color: grey;
}
.s-isActive:hover{
    color: #990000;
}
.s-notActive:hover{
    color: #474747;
}
</style>