doc_man/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations'}
  authenticate :user do
      resources :documents do
        get 'categories', on: :member
        resources :suggestions do
          resources :suggestion_user_comments
        end
      end
      resources :categories
      resources :users
      root to: 'documents#index'
      get "my_documents" => 'documents#my_documents_index', :as => :my_documents
      get "/add_like" => "likes#addLike"
      get "/remove_like" => "likes#removeLike"
  end
  get "public_documents" => 'documents#public_documents_index', :as => :public_documents
  get "public_show" => 'documents#public_show', :as => :public_show
  get "/test" => "documents#markdownHtml"
  post "/collaborators" => "documents#updateCollaborators"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

doc_man/app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :document
  belongs_to :user
  has_many :suggestion_user_comments,  dependent: :destroy 

  validates :text, {
  	length: { minimum: 1,  maximum: 500 },
  	presence: true
  	}

  def has_access(current_user)
  	collaborators = document.users
    if collaborators.include? current_user or current_user == user
  	   return true
    else
       return false
    end
  end


end

doc_man/app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    document_id = params[:document_id]
    @document = Document.find(document_id)
    @suggestions = @document.suggestions
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion_user_comment = SuggestionUserComment.new
    document_id = params[:document_id]
    @document = Document.find(document_id)
    @suggestions = Suggestion.find(params[:id])
    @comments = @suggestions.suggestion_user_comments

  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
    @document = Document.find(params[:document_id])
  end

  # GET /suggestions/1/edit
  def edit
    document_id = params[:document_id]
    @document = Document.find(document_id)
    collaborators = @document.users
    if not collaborators.include? current_user and current_user != @suggestion.user
      redirect_to document_suggestions_url, alert: 'Unable to edit this suggestion.'
    end
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)
    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to document_suggestion_url(params[:suggestion][:document_id],@suggestion), notice: 'Suggestion was successfully created.' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to document_suggestions_url, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { redirect_to edit_document_suggestion_path(@suggestion.document, @suggestion), alert: 'Failed to edit Suggestion, '+@suggestion.errors.full_messages[0]+'.' }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    document_id = params[:document_id]
    document = Document.find(document_id)
    collaborators = document.users
    if collaborators.include? current_user or current_user == @suggestion.user
      @suggestion.destroy
      respond_to do |format|
        format.html { redirect_to document_suggestions_url, notice: 'Suggestion was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to document_suggestions_url, alert: 'Unable to destroy this suggestion.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params
      params.require(:suggestion).permit(:document_id, :user_id, :text, :status)
    end
end

doc_man/app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

doc_man/app/views/suggestions/_form.html.erb
<%= form_for ([document, suggestion]) do |f| %>
  <% if suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field(:document_id, :value => params[:document_id]) %>
  </div>

  <div class="field">
    <%= f.hidden_field(:user_id, :value => current_user.id) %>
  </div>
  <div class="panel panel-primary" >
    <div class = "panel-heading">
  		<h2>
  			<strong><%= action %> - <a href="<%= document_path(document) %>" style="color:white;">[<%= document %>]</a></strong>
  		</h2>
  	</div>
    <div class="panel-body">
        <div class="field">
          <%= f.text_area :text, style: "margin: 0px; height: 110px; width: 100%;" %>
        </div>
    </div>
    <div class="panel-footer">
  			<div class = "row">
  				<div class = "col-md-6" align = "left">
            <div class="actions">
                <%= f.submit :class => "btn btn-success" %> |
                <%= link_to 'Back', document_suggestions_path, class: "btn btn-danger", style: "color:white" %>
            </div>
  				</div>
  				<div class = "col-md-6" align = "right">
            <div class="field">
              <% if suggestion.status.nil? %>
                <%= f.hidden_field(:status, :value => 'Pending') %>
              <% else %>
                <%= f.label :status %>
                <%=  f.select :status, ['Pending', 'Rejected', 'Implemented'] %>
              <% end %>
            </div>
  				</div>
  			</div>
  	</div>
  </div>

<% end %>

doc_man/app/views/suggestions/edit.html.erb
<%= render 'form', document: @document, suggestion: @suggestion, action: "Editting Suggestion #"+@suggestion.id.to_s %>

doc_man/app/views/suggestions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      Suggestions for:
        <i><a href="<%= document_path(@document) %>" style="color:black;"><%= @document %></a></i>
    </h1>
  </div>
<table class='table table-hover table-striped'>
  <thead>
    <tr>
      <th>User</th>
      <th>Text</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.user %></td>
        <td><%= truncate(suggestion.text.html_safe, length:75) %></td>
        <td><%= suggestion.status %></td>
        <td><%= link_to 'Show', document_suggestion_path(suggestion.document,suggestion), class: "btn btn-info", style: "color:white" %></td>
        <% if suggestion.has_access(current_user) == true %>
          <td><%= link_to 'Edit', edit_document_suggestion_path(id: suggestion.id), class: "btn btn-primary", style: "color:white" %></td>
          <td><%= link_to 'Destroy',  document_suggestion_path(suggestion.document, suggestion), class: "btn btn-danger", style: "color:white",method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to 'New Suggestion', new_document_suggestion_path, class: "btn btn-primary", style: "color:white" %>
<%= link_to 'Back', documents_path, class: "btn btn-success", style: "color:white" %>

doc_man/app/views/suggestions/new.html.erb
<%= render 'form', document: @document, suggestion: @suggestion, action: "New Suggestion" %>

doc_man/app/views/suggestions/show.html.erb
<div class="panel panel-primary">
	<div class = "panel-heading">
		<h2>
			<strong>Suggestion #<%= @suggestion.id %>:</strong>
	  		<a href="<%= document_path(@suggestion.document) %>" style="color:white;">[<%= @suggestion.document %>]</a>
		</h2>
		<h4>
			<strong>Suggested by:</strong>
			<%= @suggestion.user %>
		</h4>
		<div class = "row">
			<div class = "col-md-12" align = "right">
				<h5>
					<strong>Posted on:</strong> <i><%= @suggestion.created_at.strftime('%a, %d %b %Y - %H:%M:%S') %></i>
				</h5>
				<h5>
					<% if @suggestion.updated_at != @suggestion.created_at %>
						<strong>Last Updated on:</strong>
						<i><%= @suggestion.updated_at.strftime('%a, %d %b %Y - %H:%M:%S') %></i>
					<% end %>
				</h5>
			</div>
		</div>
	</div>

	<div class="panel-body">
    <p>
      <%= @suggestion.text %>
    </p>
  </div>
	<div class="panel-footer">
			<div class = "row">
				<div class = "col-md-6" align = "left">
				  <%= link_to 'Edit', edit_document_suggestion_path(id: @suggestion.id), class: "btn btn-primary", style: "color:white" %> |
				  <%= link_to 'Back', document_suggestions_path, class: "btn btn-success", style: "color:white" %>
				</div>
				<div class = "col-md-6" align = "right">
					<strong>Status:</strong>
					<%= @suggestion.status %>
				</div>
			</div>
	</div>
</div>
<div>
	<% @comments.each do |comment| %>

<div class="modal fade" id="exampleModal<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" >
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLabel">
        	Edit comment
        </h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "suggestion_user_comments/form",:action => '#suggestion_user_comments#edit',locals:{document: @document,suggestion: @suggestion ,suggestion_user_comment: comment} %>       
      </div>
    </div>
  </div>
</div>

	<div class="container">
	  <h5>
	  	 <strong>
	  	 	<%= comment.user %> :
	  	 </strong>
	  </h5>
	  <div class="panel panel-default" style="width:1100px;">
	    <div class="panel-heading">
			<p>
			  <%= comment.comment %>
			</p>
	    </div>
			<div class="panel-body">
				<div class = "row">
			    <% if comment.has_access(current_user) %>
						<div class = "col-md-6" align = "left">
							<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal<%= comment.id %>" >
							  Edit
							</button>
							<%= link_to 'Destroy',   document_suggestion_suggestion_user_comment_path(@suggestion.document, @suggestion, comment.id), class: "btn btn-danger", style: "color:white",method: :delete, data: { confirm: 'Are you sure?' } %>
						</div>
						<div class = "col-md-6" align = "right">
				<% else %>
						<div class = "col-md-12" align = "right">

				<% end %>

			<div>
				<strong>Posted on:</strong>
				<i><%= comment.created_at.strftime('%a, %d %b %Y - %H:%M:%S') %></i>
			</div>
			<div>
				<% if comment.updated_at != comment.created_at %>
					<strong>Last Updated on:</strong>
					<i><%= comment.updated_at.strftime('%a, %d %b %Y - %H:%M:%S') %></i>
				<% end %>
			</div>
		</div>
	</div>
 </div>
	  </div>
	</div>
	<% end %>

	<div>
		<div>
			<h4>
				<strong>Add a comment: </strong>
			</h4>
		</div>

		<div>
			<%= render partial: "suggestion_user_comments/form",locals:{document: @document,suggestion: @suggestion ,suggestion_user_comment: @suggestion_user_comment} %> 
			<%= link_to 'Back', document_suggestions_path, class: "btn btn-success", style: "color:white" %>
		</div>
	</div>
</div>